### ISSUE TITLE
update favicon

### ISSUE THREAD

**Issue by Dhaiwat10** [Dhaiwat10/web3cheatsheet#9]
let's use the D_D logo as our favicon

**Comment by tripathii-devv** [comment]
Hey! I am interested in contributing.. can you please be more specific which kinda favicon you want ?

**Comment by Dhaiwat10** [comment]
@tripathii-devv this logo: https://github.com/Developer-DAO/web3cheatsheet/blob/main/public/d_d.svg

**Comment by tripathii-devv** [comment]
> @tripathii-devv this logo: https://github.com/Developer-DAO/web3cheatsheet/blob/main/public/d_d.svg
Thankyou, I'll be honest that I am a beginner but give me some time I'll try to figure out and contribute to the project.

**Comment by Dhaiwat10** [comment]
Closed via #10
